name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B -DskipTests clean package

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: alfresco-totp-authenticator-platform.jar
          path: alfresco-totp-authenticator-platform/target/*.jar

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: alfresco-totp-authenticator-share.jar
          path: alfresco-totp-authenticator-share/target/*.jar
